# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/Users/chaos/projects/FangYen/HieroglyphVM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/Users/chaos/projects/FangYen/HieroglyphVM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/chaos/projects/FangYen/HieroglyphVM/CMakeFiles C:/Users/chaos/projects/FangYen/HieroglyphVM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/chaos/projects/FangYen/HieroglyphVM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HieroglyphVM

# Build rule for target.
HieroglyphVM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HieroglyphVM
.PHONY : HieroglyphVM

# fast build rule for target.
HieroglyphVM/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/build
.PHONY : HieroglyphVM/fast

src/chunk.obj: src/chunk.c.obj
.PHONY : src/chunk.obj

# target to build an object file
src/chunk.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/chunk.c.obj
.PHONY : src/chunk.c.obj

src/chunk.i: src/chunk.c.i
.PHONY : src/chunk.i

# target to preprocess a source file
src/chunk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/chunk.c.i
.PHONY : src/chunk.c.i

src/chunk.s: src/chunk.c.s
.PHONY : src/chunk.s

# target to generate assembly for a file
src/chunk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/chunk.c.s
.PHONY : src/chunk.c.s

src/disassembler.obj: src/disassembler.c.obj
.PHONY : src/disassembler.obj

# target to build an object file
src/disassembler.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/disassembler.c.obj
.PHONY : src/disassembler.c.obj

src/disassembler.i: src/disassembler.c.i
.PHONY : src/disassembler.i

# target to preprocess a source file
src/disassembler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/disassembler.c.i
.PHONY : src/disassembler.c.i

src/disassembler.s: src/disassembler.c.s
.PHONY : src/disassembler.s

# target to generate assembly for a file
src/disassembler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/disassembler.c.s
.PHONY : src/disassembler.c.s

src/loader.obj: src/loader.c.obj
.PHONY : src/loader.obj

# target to build an object file
src/loader.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/loader.c.obj
.PHONY : src/loader.c.obj

src/loader.i: src/loader.c.i
.PHONY : src/loader.i

# target to preprocess a source file
src/loader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/loader.c.i
.PHONY : src/loader.c.i

src/loader.s: src/loader.c.s
.PHONY : src/loader.s

# target to generate assembly for a file
src/loader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/loader.c.s
.PHONY : src/loader.c.s

src/main.obj: src/main.c.obj
.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/main.c.s
.PHONY : src/main.c.s

src/memory.obj: src/memory.c.obj
.PHONY : src/memory.obj

# target to build an object file
src/memory.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/memory.c.obj
.PHONY : src/memory.c.obj

src/memory.i: src/memory.c.i
.PHONY : src/memory.i

# target to preprocess a source file
src/memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/memory.c.i
.PHONY : src/memory.c.i

src/memory.s: src/memory.c.s
.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/memory.c.s
.PHONY : src/memory.c.s

src/value.obj: src/value.c.obj
.PHONY : src/value.obj

# target to build an object file
src/value.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/value.c.obj
.PHONY : src/value.c.obj

src/value.i: src/value.c.i
.PHONY : src/value.i

# target to preprocess a source file
src/value.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/value.c.i
.PHONY : src/value.c.i

src/value.s: src/value.c.s
.PHONY : src/value.s

# target to generate assembly for a file
src/value.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/value.c.s
.PHONY : src/value.c.s

src/vm.obj: src/vm.c.obj
.PHONY : src/vm.obj

# target to build an object file
src/vm.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/vm.c.obj
.PHONY : src/vm.c.obj

src/vm.i: src/vm.c.i
.PHONY : src/vm.i

# target to preprocess a source file
src/vm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/vm.c.i
.PHONY : src/vm.c.i

src/vm.s: src/vm.c.s
.PHONY : src/vm.s

# target to generate assembly for a file
src/vm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HieroglyphVM.dir/build.make CMakeFiles/HieroglyphVM.dir/src/vm.c.s
.PHONY : src/vm.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HieroglyphVM"
	@echo "... src/chunk.obj"
	@echo "... src/chunk.i"
	@echo "... src/chunk.s"
	@echo "... src/disassembler.obj"
	@echo "... src/disassembler.i"
	@echo "... src/disassembler.s"
	@echo "... src/loader.obj"
	@echo "... src/loader.i"
	@echo "... src/loader.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory.obj"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/value.obj"
	@echo "... src/value.i"
	@echo "... src/value.s"
	@echo "... src/vm.obj"
	@echo "... src/vm.i"
	@echo "... src/vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

